baseURL = 'https://msoucy.me/'
languageCode = 'en-us'
title = 'msoucy.me'
theme = 'msoucy'
enableGitInfo = true

[params]
  author = 'Matt Soucy'
  fb = "1188604437"
  subtitle = "Code, games, and sarcasm"

[taxonomies]
  category = 'categories'
  tag = 'tags'
  series = 'series'

[social]
  twitter = 'msoucy93'
